name: Deploy Maven Release

on:
  workflow_dispatch: {}
  release:
    types: [published]
concurrency:
  group: release
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: ./mvnw --batch-mode test verify --file pom.xml
  build:
    runs-on: ubuntu-24.04
    needs: test
    environment:
      name: release
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Build package
        run: ./mvnw --batch-mode package --file pom.xml
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: target/*.war
      - name: Deploy package
        id: deployment
        run: ./mvnw --batch-mode deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: staging
      url: ${{ steps.deployment.outputs.url }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: sed -i 's|http://localhost:8080/|${{ secrets.TOMCAT_HOST }}|g' pom.xml
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
          server-id: TomcatServer
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy package
        run: ./mvnw --batch-mode tomcat7:deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.TOMCAT_USER }}
          MAVEN_PASSWORD: ${{ secrets.TOMCAT_PASS }}
